name: 自动更新直播源

on:
  schedule:
    # 每1小时运行一次（UTC时间）
    - cron: '0 */1 * * *'
  workflow_dispatch:  # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出仓库
      uses: actions/checkout@v4
      
    - name: 设置 Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: 安装依赖
      run: pip install pytz
      
    - name: 运行更新脚本
      run: python update_script.py
      env:
        TZ: Asia/Shanghai  # 设置时区
        
    - name: 提交更改
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add live.m3u
        git commit -m "自动更新直播链接 [$(date +'%Y-%m-%d %H:%M:%S')]"
        git push
