name: 自动更新河北卫视直播源
on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        
      - name: 生成直播链接
        run: |
          # 计算当前时间戳
          TIMESTAMP=$(date +%s)
          
          # 生成密钥 (使用算法: MD5("hebtv" + 时间戳)
          KEY=$(echo -n "hebtv$TIMESTAMP" | md5sum | awk '{print $1}')
          
          # 创建直播源内容
          echo "#EXTM3U" > live.m3u
          echo "#EXTINF:-1,河北卫视" >> live.m3u
          echo "https://tv.pull.hebtv.com/jishi/weishipindao.m3u8?t=$TIMESTAMP&k=$KEY" >> live.m3u
          
          # 显示结果
          echo "生成的直播链接:"
          echo "https://tv.pull.hebtv.com/jishi/weishipindao.m3u8?t=$TIMESTAMP&k=$KEY"
          
      - name: 提交更改
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add live.m3u
          git commit -m "自动更新直播链接"
          git push
