name: 自动更新直播源
on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      # 步骤1：检出仓库（关键修复）
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 必须添加
          fetch-depth: 0  # 获取完整历史
          
      # 步骤2：设置Python环境
      - name: 设置Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # 指定明确版本
          
      # 步骤3：生成直播链接（简化版）
      - name: 生成直播链接
        run: |
          # 获取当前时间戳
          TIMESTAMP=$(date +%s)
          
          # 生成河北卫视密钥
          KEY_Hebei=$(echo -n "hebtv$TIMESTAMP" | md5sum | awk '{print $1}')
          
          # 创建M3U文件
          echo "#EXTM3U" > live.m3u
          echo "#EXTINF:-1,河北卫视" >> live.m3u
          echo "https://tv.pull.hebtv.com/jishi/weishipindao.m3u8?t=$TIMESTAMP&k=$KEY_Hebei" >> live.m3u
          
          # 添加河南卫视（静态源示例）
          echo "#EXTINF:-1,河南卫视" >> live.m3u
          echo "http://hw-m-l.cztv.com/channels/lantian/channel010/1080p.m3u8" >> live.m3u
          
          # 显示结果
          echo "✅ 直播列表已生成"
          cat live.m3u
          
      # 步骤4：提交更改（关键修复）
      - name: 提交更改
        run: |
          # 配置Git用户
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          
          # 添加并提交更改
          git add live.m3u
          git commit -m "自动更新直播链接"
          
          # 强制推送（避免冲突）
          git push --force
