name: 自动更新直播源
on:
  schedule:
    - cron: '0 * * * *'  # 每小时运行一次
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          
      - name: 生成并测试河北卫视链接
        run: |
          TIMESTAMP=$(date +%s)
          KEY_Hebei=$(echo -n "hebtv$TIMESTAMP" | md5sum | awk '{print $1}')
          URL="https://tv.pull.hebtv.com/jishi/weishipindao.m3u8?t=$TIMESTAMP&k=$KEY_Hebei"
          
          # 测试带请求头的链接
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" -H "Referer: https://www.hebtv.com/" -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36" "$URL")
          
          if [ "$STATUS" -eq 200 ]; then
            echo "✅ 链接有效: $URL"
            echo "$URL" > hebei_url.txt
          else
            echo "❌ 链接无效(状态码:$STATUS)，使用备用源"
            echo "https://liveplay-hhht.cctv.cn/hd/250.m3u8" > hebei_url.txt
          fi
          
      - name: 添加河南卫视
        run: |
          echo "http://hw-m-l.cztv.com/channels/lantian/channel010/1080p.m3u8" > henan_url.txt
          
      - name: 创建播放列表
        run: |
          URL_Hebei=$(cat hebei_url.txt)
          URL_Henan=$(cat henan_url.txt)
          
          echo "#EXTM3U" > live.m3u
          echo "#EXTINF:-1,河北卫视" >> live.m3u
          echo "$URL_Hebei" >> live.m3u
          echo "#EXTINF:-1,河南卫视" >> live.m3u
          echo "$URL_Henan" >> live.m3u
          
          echo "播放列表内容："
          cat live.m3u
          
      - name: 提交更改
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add live.m3u
          git commit -m "更新直播链接"
          git push
